version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ProductMicroService.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ProductMicroServiceConnection=Host=postgres;Port=5432;Database=ProductDb;Username=postgres;Password=hosar860088
    networks:
      - product-network

  postgres:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_DB: ProductDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hosar860088
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - product-network

volumes:
  pgdata:

networks:
  product-network:
